# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('resumen', models.TextField(blank=True, verbose_name='Resumen')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('enlace', models.TextField(blank=True, verbose_name='Enlace')),
                ('fecha_de_revision', models.DateField(blank=True, default=datetime.date.today, verbose_name='Fecha de revisión')),
            ],
        ),
    ]
