# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='enlace',
            field=models.URLField(blank=True, verbose_name='Enlace'),
        ),
    ]
