# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20160910_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Categoría')),
            ],
        ),
        migrations.AddField(
            model_name='web',
            name='categoria',
            field=models.ManyToManyField(to='websites.Categoria'),
        ),
    ]
