# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_web_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, verbose_name='slug'),
        ),
    ]
