# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 23:35
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_web_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=10)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paleta_de_colores', to='websites.Web')),
            ],
            options={
                'verbose_name_plural': 'Paleta de colores',
                'verbose_name': 'Color',
            },
        ),
    ]
