# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 00:36
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_webcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=10),
        ),
    ]
