# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionNosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título')),
                ('detalle', models.TextField(verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Bloque de sección Nosotros',
                'verbose_name_plural': 'Sección Nosotros',
            },
        ),
    ]
