# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccionnosotros',
            options={'ordering': ['position'], 'verbose_name': 'Bloque de sección Nosotros', 'verbose_name_plural': 'Sección Nosotros'},
        ),
    ]
