# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20160911_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha/Hora')),
                ('estado', models.CharField(default='P', max_length=1, verbose_name='Estado')),
                ('nombres', models.CharField(max_length=32, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('asunto', models.CharField(max_length=48, verbose_name='Asunto')),
                ('detalle', models.TextField(verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Formulario de Contacto',
                'verbose_name_plural': 'Formularios de Contacto',
            },
        ),
    ]
