# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionLegal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=0, verbose_name='Posición')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título')),
                ('detalle', models.TextField(verbose_name='Detalle')),
            ],
            options={
                'verbose_name_plural': 'Sección Legal',
                'verbose_name': 'Bloque de sección Lega',
                'ordering': ['position'],
            },
        ),
    ]
